# Generated by Django 4.2.4 on 2023-08-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('release_date', models.DateField()),
                ('version', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('documentation', models.URLField()),
                ('popularity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_rank', models.PositiveIntegerField()),
                ('performance', models.TextField()),
                ('community_support', models.TextField()),
                ('package_manager', models.CharField(max_length=50)),
                ('desktop_environment', models.CharField(max_length=50)),
                ('architectures', models.CharField(max_length=200)),
                ('license', models.CharField(max_length=50)),
                ('pros_and_cons', models.TextField()),
                ('security_features', models.TextField()),
                ('installation_method', models.TextField()),
                ('package_repositories', models.TextField()),
            ],
        ),
    ]
